### ISSUE TITLE
[Feature]: Add support to trap removal

### ISSUE THREAD

**Issue by michaelyoukeim** [soot-oss/SootUp#1010]
### Missing Feature

The `StmtGraph` class lacks a `removeTrap` method, which would provide a direct way to remove traps. Currently, traps can only be removed by removing the associated exception from `MutableBasicBlock` or `MutableBlockStmtGraph`, which is less straightforward.

**Comment by swissiety** [comment]
the current way would be to remove the exception from the MutableBasicBlock / MutableBlockStmtGraph - but a method could be a nice enhancement
