### ISSUE TITLE
[Refactor]: Pom make use of central dependencymanagement for submodules in the reactor pom

### ISSUE THREAD

**Issue by swissiety** [soot-oss/SootUp#1012]
like its done in [SparseBoomerang](https://github.com/secure-software-engineering/SparseBoomerang)
- [ ] remove`<version>${project.version}</version>` in every submodule pom

**Comment by sahilagichani14** [comment]
Yes, this would be helpful. I was trying to use sootup.codepropertygraph PropertyGraph ddgGraph in sootup.java.core, maven says cyclic dependency detected since codepropertygraph module already using java.core module in dependency.

**Comment by victoraysev** [comment]
Hi! Could you assign this issue to me? I would love to contribute this repository

**Comment by swissiety** [comment]
closed by #1018
