### ISSUE TITLE
[Feature]: Get Performance of BodyInterceptors (Runtime and Memory Consumption)

### ISSUE THREAD

**Issue by sahilagichani14** [soot-oss/SootUp#1035]
### Missing Feature

As a user, I want to know how much time and memory each body interceptor uses so I can choose which ones to apply in the view for better performance.

**Comment by swissiety** [comment]
*They are not really a Buffet - some of the default `BodyInterceptor`s are (quite) **mandatory** to apply if you want to get some reasonable/valid Jimple code.

**Comment by swissiety** [comment]
For the Time measurements: you could create a generic BodyInterceptor implementation that wraps an actual BodyInterceptor and measures/stores/prints/... the time spent in the wrapped BodyInterceptor.intercept() method.

**Comment by sahilagichani14** [comment]
> For the Time measurements: you could create a generic BodyInterceptor implementation that wraps an actual BodyInterceptor and measures/stores/prints/... the time spent in the wrapped BodyInterceptor.intercept() method.

Yes, I did the same :) I'm printing the measured time & memory usage by each of the specified interceptors list on individual body.
