### ISSUE TITLE
[Bug]: getType of JArrayRef is not element's type

### ISSUE THREAD

**Issue by Liyw979** [soot-oss/SootUp#1076]
### What happened?

test code
```
class Foo {
    public static void main(String[] args) {
        System.out.println("1" + args[0]);
    }
}
```
debugger view:
![image](https://github.com/user-attachments/assets/1d787e5e-0021-4a3c-a757-cf6fb40af62e)
![image](https://github.com/user-attachments/assets/808a08a9-c017-4ae0-a726-679d67b72023)

relevant code:
https://github.com/soot-oss/SootUp/blob/d6d411f6cea8b7047dc40bc86f81c518a1845f34/sootup.core/src/main/java/sootup/core/jimple/common/ref/JArrayRef.java#L84-L88

I am expecting the return type of `arrayref` to be `String` instead of `String[]`, am i right?

### Version

Latest develop branch

**Comment by swissiety** [comment]
lets check what soot did there

**Comment by Liyw979** [comment]
https://github.com/soot-oss/soot/blob/9616935197b96c93322612e27dc4eb318c11f4a0/src/main/java/soot/jimple/internal/JArrayRef.java#L136-L160

**Comment by swissiety** [comment]
Thx! Yes that makes sense as the JArrayRef would point to the actual element of the array.
