### ISSUE TITLE
[Improve]: Update asm constant to make SootUp working with Java 23/24 .class files

### ISSUE THREAD

**Issue by JaktensTid** [soot-oss/SootUp#1147]
### What happened?

Something did not work as expected..

```java
public class Main {
    public static void main(String[] args) {
        AnalysisInputLocation inputLocation = new JavaClassPathAnalysisInputLocation("/home/jt/IdeaProjects/JavaParserTest1/target/classes");
        var inputLocations = new ArrayList<AnalysisInputLocation>();
        inputLocations.add(inputLocation);
        JavaView view = new JavaView(inputLocations);
        var classes = view.getClasses();
    }
}
```

var classes array is empty

![image](https://github.com/user-attachments/assets/543b4d64-5e63-43db-a2e8-4aff2f8678d9)

### Version

Latest develop branch

**Comment by JaktensTid** [comment]
Ok, got it. There was a warning about logging and warning about incorrect java compilation version was suppressed

**Comment by swissiety** [comment]
we need to update the library/a constant and maybe adapt bytecode handling - lets see: https://asm.ow2.io/versions.html

**Comment by JaktensTid** [comment]
> we need to update the library/a constant and maybe adapt bytecode handling - lets see: https://asm.ow2.io/versions.html

Yeah, I compiled .class files using 67 ver, but soot requires 65
