### ISSUE TITLE
Type Inference for the bytecode frontend

### ISSUE THREAD

**Issue by linghuiluo** [soot-oss/SootUp#165]
- [x] Create an API to intercept and transform method bodies (#189)
- [ ] Implement interceptor stages according to [BELLAMY, Ben, et al. Efficient local type inference. In: ACM Sigplan Notices. ACM, 2008. S. 475-492.] https://pdfs.semanticscholar.org/9c88/b316d2e96256f2cb73177a3d045a67d77f25.pdf  in the bytecode frontend module

**Comment by kadirayk** [comment]
addressed in https://github.com/soot-oss/SootUp/pull/465
