### ISSUE TITLE
How to set builtin class in classpath on jdk17

### ISSUE THREAD

**Issue by ox1234** [soot-oss/SootUp#522]
I want to find a class's super class in jdk17, but Sootup report an error, it seems builtin class is not in View.How i set these builtin classes?
![image](https://user-images.githubusercontent.com/32171650/208014002-73524465-5787-4f17-8ff8-d7a1d4e1c70c.png)

**Comment by swissiety** [comment]
Hi @ox1234,
did you add the `JrtFileSystemAnalysisInputLocation()` to the Projects AnalysisInputLocations?
If not please share your Project configuration with us.

**Comment by ox1234** [comment]
> Hi @ox1234, did you add the `JrtFileSystemAnalysisInputLocation()` to the Projects AnalysisInputLocations? If not please share your Project configuration with us.

Thanks, it works for me.
