### ISSUE TITLE
Build fail, some files are skipped

### ISSUE THREAD

**Issue by ox1234** [soot-oss/SootUp#526]
[WARNING] skip failed file : Could not extract header on file /home/flight/projects/java/SootUp/sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/BytecodeClassLoadingOptions.java for reason copyright [Copyright (C) 2019-2020 Christian Brüggemann] is not valid
org.codehaus.mojo.license.header.InvalideFileHeaderException: Could not extract header on file /home/flight/projects/java/SootUp/sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/BytecodeClassLoadingOptions.java for reason copyright [Copyright (C) 2019-2020 Christian Brüggemann] is not valid

**Comment by ox1234** [comment]
I use the document to install sootup. But in the final jar it missing many classes, such as JavaSootMethod, etc

**Comment by ox1234** [comment]
Here is the build log:
[build.txt](https://github.com/soot-oss/SootUp/files/10301461/build.txt)

**Comment by ox1234** [comment]
only use this way, it can be import in project:
```xml
<dependencies>
        <!-- https://mvnrepository.com/artifact/commons-cli/commons-cli -->
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.5.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.maven/maven-model -->
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-model</artifactId>
            <version>3.8.5</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.java.core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.java.core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.callgraph</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.analysis</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.java.sourcecode</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.jimple.parser</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.soot-oss</groupId>
            <artifactId>sootup.java.bytecode</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

**Comment by kadirayk** [comment]
exactly, in docs we only show the sootup.core module as an example but you should add all the modules you need as a dependency.

**Comment by ox1234** [comment]
> exactly, in docs we only show the sootup.core module as an example but you should add all the modules you need as a dependency.

That's very confused. Maybe should add some note in the docs or just have a mechanism to package all modules in one jar?

**Comment by kadirayk** [comment]
Thanks a lot for the feedback. I updated the docs accordingly.
