### ISSUE TITLE
Is it possible to integrate QilinPTA into SootUp?

### ISSUE THREAD

**Issue by DongjieHe** [soot-oss/SootUp#532]
Dear SootUp developers：
I have great interest in integrating our new Java pointer analysis framework built on top of Soot/Spark, QilinPTA, into SootUp.  I create this issue to get your opinion. 

I am the principal developer of QilinPTA ([https://github.com/QilinPTA/Qilin.git](https://github.com/QilinPTA/Qilin.git)). Our framework is not only precise( achieving the same precision as the state-of-the-art) but also efficient (more than 2 times faster than the state-of-the-art). Our framework supports various kinds of context sensitivity, such as call-site sensitivity,   object sensitivity, and type sensitivity. To support recent advances in selective context sensitivity, our framework is the first framework to support fine-grained context sensitivity at the variable level.

I am glad that SootUp could support analyzing Java bytecode of recent Java compilers such as Java 17. I am eager to integrate QilinPTA into SootUP and find that Spark (a context-insensitive special case of QilinPTA) is still under development. Thus, I am writing this email to ask whether it is possible to integrate QilinPTA into SootUp.

Looking forward to your reply, Thanks.

Kind regards,

Dongjie He

**Comment by JonasKlauke** [comment]
Dear Dongjie He,

Thank you for your interest in SootUp. Sorry for the late reply, holiday vacations. I am not sure if I have understood your question correctly. Are you asking to integrate your tool into SootUp (as a submodule) or do you want to know if SootUp is already capable to calculate the necessary information for pointer analysis? In either case - can you specify which features of Soot do you make use of in your current approach?

Yes you are correct. Spark is still in development and not yet added to SootUp. But we support CHA and RTA without Spark.

Best regards
Jonas

**Comment by DongjieHe** [comment]
Dear Jonas,
I am asking to integrate Qilin into SootUp as a submodule. Qilin supports different flavors of context-sensitive pointer analyses and thus treats Spark (the context-insensitive pointer analysis) as a special case. 

Best regards,
Dongjie

**Comment by JonasKlauke** [comment]
Dear Dongjie,

thank you for your motivation to extend SootUp. I think the best way to integrate your submodule would be to fork the current repository and create a pull request after your first stable version. Feel free to ask questions in the discussion section. 
SootUp is currently still in an early development phase so we hope we provide all features you need. 

Best Regards 
Jonas

**Comment by DongjieHe** [comment]
Dear Jonas,
I must have missed the last message about this issue.
Thanks for allowing me to integrate Qilin into SootUp as a submodule. I will try my best to integrate Qilin as a submodule to SootUp on my end. Once I get a stable version, I will create a pull request. Thanks anyway.

Best regards,
Dongjie He

**Comment by JonasKlauke** [comment]
No problem :)
Feel free to ask questions in https://github.com/soot-oss/SootUp/discussions

I will close the issue
