### ISSUE TITLE
 Add gradle support

### ISSUE THREAD

**Issue by YaphetsH** [soot-oss/SootUp#535]
Is there any plan about add gradle dsl support?

**Comment by JonasKlauke** [comment]
Hi,
Are you asking if we plan to enable to build SootUp with gradle instead of maven?
It is currently not planned but we can look into it, but currently we are focused on other higher priority issues.

But you can add gradle support, if you want :)

**Comment by swissiety** [comment]
If you want to use SootUp with gradle have a look at https://soot-oss.github.io/SootUp/latest/installation/#__tabbed_1_2
