### ISSUE TITLE
Is there a plan to implement traditional data flow algorithms in analysis module?

### ISSUE THREAD

**Issue by t3ls** [soot-oss/SootUp#536]
Like Worklist algorithm, correspond to `ForwardFlowAnalysis` in Soot.

**Comment by ericbodden** [comment]
Hi there. For the inter-procedural case, you can use SootUp with Heros. That should work like a charme. Or do you have a use case for an intra-procedural analysis?

**Comment by kadirayk** [comment]
Hi, yes we plan to extend the analysis module with intra-procedural analysis support.

**Comment by t3ls** [comment]
Hi, excited to here that. And will you add points-to analysis too?

**Comment by dialectically** [comment]
Hi there, just want to know that is there a way  I can use inter-procedural module to do a intra-procedural analysis?

**Comment by kadirayk** [comment]
I think it should be possible, you can give it a try by just implementing normal flow functions and returning the identity flow function (`Identity.v()`) in case of call, call-to-return, and return flow functions.

**Comment by dialectically** [comment]
sounds great, I'm going to try on this. thx.

**Comment by ericbodden** [comment]
@kadirayk one would probably need to use KillAll in case of "call", no?

**Comment by kadirayk** [comment]
> @kadirayk one would probably need to use KillAll in case of "call", no?

Oh yes, you are right!

**Comment by dialectically** [comment]
I got you, thanks very much for your help!

**Comment by ericbodden** [comment]
Closing for now, please reopen if more help is needed
