### ISSUE TITLE
Does SootUp support ICFG?

### ISSUE THREAD

**Issue by zhangrp666** [soot-oss/SootUp#550]
Does SootUp support ICFG?

**Comment by kadirayk** [comment]
We have an implementation here: [JimpleBasedInterproceduralCFG](https://github.com/soot-oss/SootUp/blob/develop/sootup.analysis/src/main/java/sootup/analysis/interprocedural/icfg/JimpleBasedInterproceduralCFG.java)
Does that work for you?

**Comment by will-leeson** [comment]
Would it be difficult to get a printer like [DotExporter](https://github.com/soot-oss/SootUp/blob/develop/sootup.core/src/main/java/sootup/core/util/DotExporter.java) for this? Essentially, it would build the CFG for all methods and then add edges between callees and callers?
