### ISSUE TITLE
Different parameter types to be passed to getMethodSubSignature in JavaIdentifierFactory are not included under the 'sootup.core.types'

### ISSUE THREAD

**Issue by DhanJaya** [soot-oss/SootUp#557]
When using the public MethodSubSignature getMethodSubSignature(@Nonnull String name, @Nonnull Type returnType, @Nonnull Iterable<? extends Type> parameterSignatures) in the JavaIdentifierFactory we need to pass the parameter types used by the method. If I need to pass Object type or any Collection type parameter what are the different Types available?

**Comment by swissiety** [comment]
Hi @DhanJaya,

if i understood you correctly you need to pass the result of  `JavaIdentifierFactory.getClasstype("java.lang.Object")` or `JavaIdentifierFactory.getClasstype("java.util.Collection")` - in case of generics: as they are type erased and therefore not modeled - so e.g. in case of  Collection<Integer> it should be enough to use the previously proposed way and just specify `JavaIdentifierFactory.getClasstype("java.util.Collection")`.

**Comment by DhanJaya** [comment]
@swissiety Thank you for clarifying this.
