### ISSUE TITLE
As a library consumer of SootUp, the release artifacts should not be fat-jars

### ISSUE THREAD

**Issue by Col-E** [soot-oss/SootUp#560]
For instance: https://repo1.maven.org/maven2/org/soot-oss/sootup.java.bytecode/1.0.0/

The JAR artifact bundles all of its dependencies. As a consumer of SootUp this prevents a user from maintaining the transitive dependency versions themselves.

**Comment by JonasKlauke** [comment]
thanks for pointing that out. The next release will not be a fatjar.

**Comment by jpstotz** [comment]
To my experience you can simply remove the whole shade plugin 

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
...
```
in the main [pom.xml](https://github.com/soot-oss/SootUp/blob/develop/pom.xml#L230-L256). 

Or is there a special use case for which jars with dependencies should be created?

**Comment by JonasKlauke** [comment]
This might be some legacy stuff, because the old soot can be used a command line tool.
