### ISSUE TITLE
dex2jar version throws MethodTooLargeException for some APKs

### ISSUE THREAD

**Issue by themoep** [soot-oss/SootUp#563]
Hi!

dex2jar v2.2 has an unfixed issue that makes it impossible to analyze very large methods. [This app (Version 1.6.6 (35) from 2023-01-10](https://f-droid.org/en/packages/dev.corruptedark.diditakemymeds/) is an example of a method failing to be translated to java.

It seems https://github.com/pxb1988/dex2jar is no longer maintained and development is more active at https://github.com/ThexXTURBOXx/dex2jar and [has fixed the issue](https://github.com/ThexXTURBOXx/dex2jar/issues/16) - I have verified that the current release v60 does not raise this Exception anymore, but the fix would require "downgrading" the pre-release 2.2 of the pxb1988/pxb1988 repo to the v60 (named 2.1) release of the ThexXTURBOXx/dex2jar repo.

If this is alright I can prepare a pull request to update the dependency.

**Comment by kadirayk** [comment]
Hi,

thanks for finding out this. We know about this fork but didn't need to switch to it so far. This makes a valid case for switching to it.  Also, you might notice we have a rather odd way of adding this dependency; we install the jar in lib to the local repo because it's not published. Not sure if v60 or the latest version can automatically be fetched instead.

**Comment by themoep** [comment]
I managed to use jitpack (see also [this related issue on ThexXTURBOXx/dex2jar](https://github.com/ThexXTURBOXx/dex2jar/issues/2)) to include it non-locally, here's the patch: https://github.com/themoep/SootUp/commit/f1989cc08329b06ff4361701bb90cbbbd1548921

However, if I do this and build my test-application using the created sootup-jars I am still running into the MethodTooLargeException. It is using the updated dex2jar because the error prints a link to the new issue tracker. If I download the dex2jar release zip and use the provided commandline tools it works and I can't find any difference in how it's called.

I haven't tried replacing the `dex-tools.jar` because the new one depends on `d2j-base-cmd.jar` and I'm not sure how to add additional files this way.

I can open a pull request to include the new dependency and remove the old one, but it currently does not fix the problem and I am out of ideas why that happens.

**Comment by evilpan** [comment]
Hi @kadirayk,
AFAIK there's a [Dexpler](https://github.com/soot-oss/soot/tree/develop/src/main/java/soot/dexpler/) converter in `Soot` which can convert Dalvik bytecode to Jimple IR directly, unlike dex2jar or dexlib which requires an extra pass to convert Dalvik bytecode to Java bytecode, and then convert to Jimple. Did you think about merging it to SootUp?

**Comment by kadirayk** [comment]
Hi @evilpan,
yes you are right. We rely on dex2jar as an interim solution, until we get dexpler running for SootUp.

**Comment by kadirayk** [comment]
@themoep thanks for the suggestion, we now get the latest version via jitpack in #615 
Not sure if it fixes the MethodTooLargeException though. I'd still close the issue since it's external.
