### ISSUE TITLE
SLF4J warning

### ISSUE THREAD

**Issue by iscas-zac** [soot-oss/SootUp#572]
Hello, I import SootUp with maven according to the [doc](https://soot-oss.github.io/SootUp/installation/), and then it prints
> SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.core/1.0.0/sootup.core-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.java.core/1.0.0/sootup.java.core-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.java.sourcecode/1.0.0/sootup.java.sourcecode-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.java.bytecode/1.0.0/sootup.java.bytecode-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.jimple.parser/1.0.0/sootup.jimple.parser-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.callgraph/1.0.0/sootup.callgraph-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~ /.m2/repository/org/soot-oss/sootup.analysis/1.0.0/sootup.analysis-1.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

I'm not sure if I am using it wrongly, but feel necessary to mention it here.

**Comment by jpstotz** [comment]
The reason is #560
