### ISSUE TITLE
SootUp fat jar issues

### ISSUE THREAD

**Issue by lehvolk** [soot-oss/SootUp#575]
It seems that SootUp jar files is a fat jars. It brings jar hell because gradle/maven can't handle transitive dependencies correctly.

Possible solutions:
- add transitive maven/gradle dependency and remove fat jar distribution
- repackage Guava, ASM etc with package prefix like sootup.com.google.*

**Comment by jpstotz** [comment]
Duplicate of #560

**Comment by JonasKlauke** [comment]
closed because it is a duplicate of #560
