### ISSUE TITLE
Broken highlighting for jimple code in docs.

### ISSUE THREAD

**Issue by intrigus-lgtm** [soot-oss/SootUp#576]
Hi, the highlighting for the jimple code in the docs is broken for the ["Local"](https://soot-oss.github.io/SootUp/jimple/#local) section.
![grafik](https://user-images.githubusercontent.com/60750685/229796387-4f5a0d86-dc34-49b8-a670-3a819f0bf6a7.png)

**Comment by JonasKlauke** [comment]
fixed
