### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by StevenArzt** [soot-oss/SootUp#590]
A Maven build of SootUp leads to a compilation problem:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project sootup.analysis: Compilation failure
[ERROR] /home/jenkins/workspace/SootUp/sootup.analysis/src/test/java/sootup/analysis/interprocedural/ifds/IFDSTaintTestSetUp.java:[83,23] cannot find symbol
[ERROR] symbol:   method createView()
[ERROR] location: variable javaProject of type sootup.java.core.JavaProject
```

This is a normal ``mvn package`` run as part of a Jenkins CI/CD job.

**Comment by JonasKlauke** [comment]
mmh I could not reproduce the issue. If I remember correcly createView is a new method introduced by the new caching strategy. Maybe your installed core dependency is outdated. Could you try to run mvn install on SootUp and check if you still have the issue?

**Comment by StevenArzt** [comment]
Problem solved, was an issue on our side. We didn't ``mvn clean`` before building.
