### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by slimming-fat** [soot-oss/SootUp#599]
Hi, can you release a new version as soon as possible, version 1.0 has too much abnormal output. I know the bug has been dealt with in the develop version.
![image](https://github.com/soot-oss/SootUp/assets/126549527/cf6d3bcd-aa12-4636-92b6-04695c98c887)

**Comment by JonasKlauke** [comment]
We plan to release a next version this  week.
If you want to use the current Dev branch you can run "mvn install" to install SootUp locally and then you can use version 1.0.0-SNAPSHOT to include the current Dev branch version.

**Comment by slimming-fat** [comment]
> We plan to release a next version this week. If you want to use the current Dev branch you can run "mvn install" to install SootUp locally and then you can use version 1.0.0-SNAPSHOT to include the current Dev branch version.

OK, Thanks you!
