### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by slimming-fat** [soot-oss/SootUp#600]
Hello, SootUp's body takes up too much memory. Is there any way to clear it when you're done?

**Comment by swissiety** [comment]
Hi,
@stschott did your caching strategy PR address that (at least on a per SootClass basis)? If yes, @Jacky-code519 please have a look at the dev branch and adapt the caching strategy used in your View.

**Comment by stschott** [comment]
Hi @Jacky-code519,
in the [documentation ](https://soot-oss.github.io/SootUp/getting-started/#creating-a-view) you can see how to use an LRUCache, which will only keep the specified amount of recently used SootClasses in memory.
This is not part of the current release (we are currently working on the new version release).
To use this feature right now, please checkout the dev branch and compile SootUp yourself.

**Comment by slimming-fat** [comment]
Thanks!
