### ISSUE TITLE
Invokedynamic failures

### ISSUE THREAD

**Issue by SoniaZaldana** [soot-oss/SootUp#619]
Hi there, 

I’ve been investigating some failures parsing invokedynamic instructions. I first saw a similar issue raised in #574.

Just noting that I originally encountered the problem in v1.0.0 but it persists in v1.1.0. 

I ran into some issues parsing record classes. I was getting various stack underrun errors when attempting to get the bodies of these methods. For example, the record class generates an equals(), hashCode() and string() method by default - all of which trigger an indy. 

```
Public record RecordTest(String a, String b) {
	public RecordTest(String a, String b) {
		this.a = a; 
		this.b = b; 
	}
}

```

When I attempt to get the method body for equals(), I get the following stack trace: 
```
Exception in thread "main" java.lang.RuntimeException: Failed to convert <jlink.RecordTest: boolean equals(java.lang.Object)>
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:201)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:95)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:166)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:134)
	at org.ifds.IFDSSetUp.setupSoot(IFDSSetUp.java:68)
	at org.ifds.IFDSSetUp.executeStaticAnalysis(IFDSSetUp.java:30)
	at org.ifds.Main.main(Main.java:15)
Caused by: java.lang.RuntimeException: Stack underrun
	at sootup.java.bytecode.frontend.OperandStack.pop(OperandStack.java:90)
	at sootup.java.bytecode.frontend.OperandStack.popImmediate(OperandStack.java:162)
	at sootup.java.bytecode.frontend.OperandStack.popImmediate(OperandStack.java:172)
	at sootup.java.bytecode.frontend.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1341)
	at sootup.java.bytecode.frontend.AsmMethodSource.convert(AsmMethodSource.java:1759)
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:198)
	... 6 more
```

I think the issue lies here https://github.com/soot-oss/SootUp/blob/v1.1.0/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1171

My understanding is we shouldn’t pop the operand stack to generate the method handle, as this leaves us with an empty stack when we generate the arguments here https://github.com/soot-oss/SootUp/blob/v1.1.0/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1354. 

I’ve currently been working around this by adding a dummy “unknown value”, as opposed to popping the operand stack. 

Aside from that, I think there some logic issues in this stretch of code: 

https://github.com/soot-oss/SootUp/blob/v1.1.0/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1383

The variable ```nrArgs``` is set to the size - 1 to account for arrays starting at 0, however in line 1391 (https://github.com/soot-oss/SootUp/blob/v1.1.0/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#LL1391C1-L1392C1), we preemptively decrease the value of nrArgs by 1 again before entering the while statement, meaning we are never popping the full extent of the operand stack. 

Finally, I think the check if the expression is a static invocation here is backwards (https://github.com/soot-oss/SootUp/blob/v1.1.0/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1394). 

If the expression is static, we’d like to pop the stack once more, not the other way around. 

Apologies for the convoluted message in advance! Resolving the 2 issues I mentioned above helped me get rid of the error messages I was getting but I’d much rather verify if this is correct. 

Thanks!

Sonia

**Comment by JonasKlauke** [comment]
Hi, 
Thanks for the investigation. 
If there is no implementation of an equal method, then there wont be a resolvable body of the method. This would be the correct signature <java.lang.Object: boolean equals(java.lang.Object)>
You can check all methods by 
```
    view.getClass(view.getIdentifierFactory().getClassType("jlink.RecordTest"))
        .ifPresent(javaSootClass -> javaSootClass.getMethods().forEach(System.out::println));
```

**Comment by swissiety** [comment]
> Hi, Thanks for the investigation. If there is no implementation of an equal method, then there wont be a resolvable body of the method. This would be the correct signature <java.lang.Object: boolean equals(java.lang.Object)> You can check all methods by
> 
> ```
>     view.getClass(view.getIdentifierFactory().getClassType("jlink.RecordTest"))
>         .ifPresent(javaSootClass -> javaSootClass.getMethods().forEach(System.out::println));
> ```
but then it would fail earlier - here the asmfrontend has found sth it tries to convert.


a) "too much pop()ing" In old [Soot](https://github.com/soot-oss/soot/blob/d8951c4cabef467e3bf1694bc1ba9c555615a3ab/src/main/java/soot/asm/AsmMethodSource.java#L1347) it seems its done like you describe - I guess its a bug introduced while porting the code. 
**// TODO** lets fix that

b) "nrArgs-1" at first glance i could not find a reason for that change.. [old soot]( https://github.com/soot-oss/soot/blob/d8951c4cabef467e3bf1694bc1ba9c555615a3ab/src/main/java/soot/asm/AsmMethodSource.java#L1572) does not do that.. maybe a failed premature optimization attempt **// TODO** investigate / revert to old soots code
hint: I remember an array that was always allocated one item too large.. but if its this piece of code the while loop was not adapted so theres 1 element less popped than in old-soot.

c) "static pop" As far as I understand it:
We don't pop (another time) because we have no base object on the stack compared to non-static

**Comment by SoniaZaldana** [comment]
Hi Markus, 

Thanks for looking into it!

Regarding (a), just wanted to note I’m not particularly interested in fetching the body for this specific method, but as you mentioned it fails earlier as asmfrontend attempts to do the conversion and that’s throwing some runtime exceptions. 

About point c, I think that makes sense to me but I am seeing some stack underrun failures with static methods. For example, the following snippet of code throws an exception [here](https://github.com/soot-oss/SootUp/blob/develop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1398). 

```
public class StaticTest {

    public static void main(String[] args) {
        AccessController.doPrivileged((PrivilegedAction<String>) () ->
                Security.getProperty(SOME_PROPERTY));
    }
}
```

```
java.lang.RuntimeException: Stack underrun
	at sootup.java.bytecode@1.1.0-SNAPSHOT/sootup.java.bytecode.frontend.OperandStack.pop(OperandStack.java:90)
	at sootup.java.bytecode@1.1.0-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.convertInvokeDynamicInsn(AsmMethodSource.java:1398)
	at sootup.java.bytecode@1.1.0-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.convert(AsmMethodSource.java:1780)
	at sootup.java.bytecode@1.1.0-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:208)
	at sootup.core@1.1.0/sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:95)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at sootup.core@1.1.0/sootup.core.model.SootMethod.getBody(SootMethod.java:134)

```

This is after patching the aforementioned issues, which I did [here](https://github.com/SoniaZaldana/SootUp/commit/29cd09c972c5e969834e3832658e10be88f156fb).

Flipping the if statement fixes the error and doesn’t seem to break non-static invocations, but I’m not sure this makes sense.  Any ideas as to what the issue could be?

**Comment by swissiety** [comment]
Hi Sonia,
I found some time to look at your patch and checked it against old soot. I recognized old soot did the conversion slightly different. Compared to your patch Soot basically created the Operand array with another element (in both cases i.e. instance/static). Maybe have a look at the branch I created (fix/convertInvokeDynamicInsn_missing_operandstack_pop) which hopefully fixes this bug as the created `Operand []` will be passed into the stackframe later via mergeIn(..) and i guess that missing element propagates.

(maybe it affects your newest #645 contribution as well? - btw: thank you for your interest in the improvement of SootUp - especially the detailed descriptions!)

**Comment by SoniaZaldana** [comment]
Hi Markus, 

Thanks for looking into it! I tried running the record class test against your branch but unfortunately the operand overrun issue still persists. 

The issue is [here](https://github.com/soot-oss/SootUp/blob/fix/convertInvokeDynamicInsn_missing_operandstack_pop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1339) when the operand stack gets [popped](https://github.com/soot-oss/SootUp/blob/fix/convertInvokeDynamicInsn_missing_operandstack_pop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1174 )  to generate the method handles. 

I think the operand stack shouldn’t be popped at that point. I tried adding a dummy unknown value as I had done on my patch to test out whether your patch fixed up the remaining issues with the ```Operand[]``` handling and I can confirm it does for the record test case. 

However, I was looking at some other cases using indy instructions. Namely [java/lang/invoke/StringConcatFactory.makeConcatWithConstants](https://github.com/openjdk/jdk-sandbox/blob/69a46c25cc87d9d5495d0bb975c44f38cbb1fe13/src/java.base/share/classes/java/lang/invoke/StringConcatFactory.java#L326). 

For example, the following statement ``` throw new IllegalArgumentException(“No recording available with id " + id)``` is setting off some [IllegalArgumentExceptions](https://github.com/soot-oss/SootUp/blob/fix/convertInvokeDynamicInsn_missing_operandstack_pop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/StackFrame.java#L93) . 

I took a quick glance and I think this is because we set the arguments for the [frame](https://github.com/soot-oss/SootUp/blob/fix/convertInvokeDynamicInsn_missing_operandstack_pop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1379) which doesn't include the instance object. 

However, when merging the frame, the ```oprs``` array also [contains](https://github.com/soot-oss/SootUp/blob/fix/convertInvokeDynamicInsn_missing_operandstack_pop/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1399) the instance object causing the size mismatch when merging. 

I'm attaching a picture of the state of oprs and the frame at the time of the exception if that is helpful 
![Screenshot from 2023-07-17 13-10-52](https://github.com/soot-oss/SootUp/assets/39814323/bbde4540-e246-4c3e-80d8-b43bb6f0cd8f)


Thanks for your help! Looking forward to sorting this out :smile:

**Comment by swissiety** [comment]
Hi Sonia,
a colleague found a regression bug introduced while porting from soot which may be the cause for your problem as well.
