### ISSUE TITLE
Dex2Jar not found for SootUp version 1.1.0

### ISSUE THREAD

**Issue by cgobel** [soot-oss/SootUp#623]
Maven: "Dependency 'com.googlecode.d2j:dex-tools:2.2-SNAPSHOT' not found"

**Comment by evilpan** [comment]
Seems that version 1.1.0 in maven is broken due to dex2jar depencency, which is fixed in https://github.com/soot-oss/SootUp/pull/615.

Should we update a new realese like `v1.1.1` to solve this and following issues? @swissiety

**Comment by kadirayk** [comment]
Version ~~1.1.1~~ 1.1.2 with this fix is available now.
