### ISSUE TITLE
Callgraph for Android app

### ISSUE THREAD

**Issue by dah-fari7009** [soot-oss/SootUp#627]
Hi,

I am trying to use SootUp for building the callgraph of a closed-source Android app. 
I see that SootUp expects an entrypoint method for callgraph construction, and in my case, I need it to be a dummy main method.
I tried running `CallGraph cg = rta.initialize();` without any arguments, but got an unexpected output:

```
GraphBasedCallGraph(38):
<com.newrelic.agent.android.Agent: void <clinit>()>:
	to <com.newrelic.agent.android.Agent: void <clinit>()>
	to <com.newrelic.agent.android.NullAgentImpl: void <clinit>()>
	to <com.newrelic.agent.android.NullAgentImpl: void <init>()>
	to <java.lang.Object: void <init>()>
	from <com.newrelic.agent.android.Agent: void <clinit>()>
	from <com.newrelic.agent.android.Agent: java.lang.String getBuildId()>
	from <com.newrelic.agent.android.util.AgentBuildOptionsReporter: void main(java.lang.String[])>
...

<java.lang.StringBuilder: java.lang.String toString()>:
	from <com.newrelic.agent.android.util.AgentBuildOptionsReporter: void main(java.lang.String[])>

<java.lang.reflect.Field: java.lang.Object get(java.lang.Object)>:
	from <com.newrelic.agent.android.Agent: java.lang.String getBuildId()>
```

 Is there an option for the tool to build a dummy main method or would I have to use a tool like FlowDroid instead for this?

Thank you!

**Comment by JonasKlauke** [comment]
SootUp does not build a dummy main method. If you dont pass an entry point the jar is checked for a main method.
The found main method is this method: <com.newrelic.agent.android.util.AgentBuildOptionsReporter: void main(java.lang.String[])>

**Comment by dah-fari7009** [comment]
Thank you for the clarifications!
