### ISSUE TITLE
classes generated from Bytecode have synchronized modifier

### ISSUE THREAD

**Issue by cgobel** [soot-oss/SootUp#630]
According to https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html a class cannot be synchronised but it is set in Jimple files. I suggest that it sets the synchronized modifier because it is the same value as ACC_SUPER (0x0020) which can be an access flag of classes.

**Comment by JonasKlauke** [comment]
thanks for finding this modifier value clash

**Comment by JonasKlauke** [comment]
Equal Modifiers:
0x0020 class: super, method synchronized
0x0040 method: bridge, field: volatile
0x0080 method: varagrs, field: transient
