### ISSUE TITLE
Operand Stack issues with ASMMethodSource

### ISSUE THREAD

**Issue by SoniaZaldana** [soot-oss/SootUp#645]
Hi folks, 

I am seeing some failures with [AsmMethodSource#convertMethodInsn](https://github.com/soot-oss/SootUp/blob/v1.1.2/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1213) with v1.1.2. 

The issue seems to lie [here](https://github.com/soot-oss/SootUp/blob/v1.1.2/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1301) where the operand stack gets popped. 

It looks like nrArgs is preemptively decreased by 1 before entering the while loop, so the popping is always off by 1.

I'm happy to open a PR with a simple patch if this makes sense. 

Thanks, 
Sonia

**Comment by kadirayk** [comment]
Hi Sonia,
thanks for the suggestion. Do you have examples that show how it fails?

**Comment by swissiety** [comment]
Hi Sonia,
I can't see an off by one bug in that section (yet?) as the (post-)decrementation of nrArgs happens after checking the loop condition.
so e.g. with nrArgs :=2 it would loop/pop the arguments 2 times (2!=0, 1!=0) and the arguments are assigned to the indices 1, 0  which makes sense to me (in the nonstatic case: code would reserve another array element where the result of popped is stored later).

**Comment by SoniaZaldana** [comment]
Hi folks, 

I think I might have jumped into the wrong conclusion. My solution was erroneously skipping a D word operand which resolved the error but not the core issue. Let me detail the issue a bit more slowly.

Note [this](https://github.com/openjdk/jdk-sandbox/blob/master/src/jdk.management.jfr/share/classes/jdk/management/jfr/FlightRecorderMXBeanImpl.java#L471 ) method for example. 

Resolving its body throws an error when interpreting the init instruction. 
```Error: Not dummy operand, virtualinvoke $stack14.<java.util.concurrent.atomic.AtomicLong: long incrementAndGet()>() -- null
java.lang.AssertionError: Not dummy operand, virtualinvoke $stack14.<java.util.concurrent.atomic.AtomicLong: long incrementAndGet()>() -- null
	at sootup.java.bytecode@1.1.2-SNAPSHOT/sootup.java.bytecode.frontend.OperandStack.popDual(OperandStack.java:100)
	at sootup.java.bytecode@1.1.2-SNAPSHOT/sootup.java.bytecode.frontend.OperandStack.pop(OperandStack.java:107)
	at sootup.java.bytecode@1.1.2-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.convertMethodInsn(AsmMethodSource.java:1305)
	at sootup.java.bytecode@1.1.2-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.convert(AsmMethodSource.java:1781)
	at sootup.java.bytecode@1.1.2-SNAPSHOT/sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:208)
	at sootup.core@1.1.2/sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:95)
	at com.google.common@31.1-jre/com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at sootup.core@1.1.2/sootup.core.model.SootMethod.getBody(SootMethod.java:134)
``` 

Stepping through the code, I can see that types corresponds to the following list per[ this line](https://github.com/soot-oss/SootUp/blob/v1.1.2/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1293) . 
![Screenshot from 2023-07-13 09-46-42](https://github.com/soot-oss/SootUp/assets/39814323/00159dcc-b395-4bce-a1f9-f408d689b473)



When we enter the [loop](https://github.com/soot-oss/SootUp/blob/v1.1.2/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/AsmMethodSource.java#L1301), it works fine until ``nArgs == 2`` when according to the types, we are supposed to pop a long. 

Note the state of the operand stack just before failing: 

![Screenshot from 2023-07-13 09-54-14](https://github.com/soot-oss/SootUp/assets/39814323/a50bee6f-9bf2-4d6d-bf5b-6c2451a6bdc9)

Therefore, when we reach this point o != o2, and we get the [assertion error.](https://github.com/soot-oss/SootUp/blob/v1.1.2/sootup.java.bytecode/src/main/java/sootup/java/bytecode/frontend/OperandStack.java#L99).


![Screenshot from 2023-07-13 10-03-49](https://github.com/soot-oss/SootUp/assets/39814323/1b969687-079c-44b6-a751-788a52f0fcf3)

Thanks for your help!

**Comment by swissiety** [comment]
@SoniaZaldana does this work now with develop?
