### ISSUE TITLE
JimpleParser class and JimpleBaseVisitor class not found

### ISSUE THREAD

**Issue by snow00726** [soot-oss/SootUp#670]
After I cloned the project to the local host and loaded the dependency, I found that sootup.jimple.JimpleBaseVisitor and sootup.jimple.JimpleParser could not be introduced into sootup.jimple.parser/src/main/java/sootup/jimple/parser/JimpleConverter.java. The pom file did not contain the dependency of these two packages, nor was it a class written by myself. I did not know what was going on and asked for help.

**Comment by swissiety** [comment]
These "missing" packages are generated on build - so a quick `mvn package` on cli  should fix that issue - or you can execute only the maven antlr plugin.
