### ISSUE TITLE
JavaIdentifierFactory's fromPath may crash when handling paths with META-INF

### ISSUE THREAD

**Issue by smartdone** [soot-oss/SootUp#675]
code: [https://github.com/soot-oss/SootUp/blob/0fbc9cf0050ef2d38291453e10a5b0f0cdba70ef/sootup.java.core/src/main/java/sootup/java/core/JavaIdentifierFactory.java#L243](https://github.com/soot-oss/SootUp/blob/0fbc9cf0050ef2d38291453e10a5b0f0cdba70ef/sootup.java.core/src/main/java/sootup/java/core/JavaIdentifierFactory.java#L243)

```
    if (path.startsWith("/META-INF/")) {
      // start at 4th separator
      int index = StringUtils.ordinalIndexOf(path, separator, 4);
      path = path.substring(index);
    }
```

StringUtils.ordinalIndexOf directly retrieves the separator's occurrence for the fourth time. If there are only three path separators, it will result in an index of -1, leading to an 'out of range' error when substring is called.

Example path: `/META-INF/quercus/com.caucho.quercus.QuercusClass`

<img width="1225" alt="image" src="https://github.com/soot-oss/SootUp/assets/7745717/8b26a3e5-2989-4e82-bc24-f599f0a2e86e">

The simplest fix:

```
if (path.startsWith("/META-INF/")) {
    // start at 4th separator
    if(StringUtils.countMatches(path, separator) >= 4){
        int index = StringUtils.ordinalIndexOf(path, separator, 4);
        path = path.substring(index);
    }
}
```

However, this fix method is not rigorous. It is still necessary to determine whether it is a multi-release JAR to ensure the correct parsing of data.

**Comment by JonasKlauke** [comment]
thanks for pointing this out. This seems to be totally useless code. The path is not used afterwards. This looks like a feature which was not completly implemented. We will look into this

**Comment by JonasKlauke** [comment]
I'm not satisfied with the way we generate the fully qualified name at the current time. Because for example spring boot puts classes and libraries in a Boot-Inf folder which results in wrong fully qualified names.

**Comment by swissiety** [comment]
`fromPath()` resembles how the default ClassLoader would search for a .class file. With that perspective we can move `fromPath()` to the PathBasedAnalysisInputLocations or remove it if its not used anymore.
