### ISSUE TITLE
Improve Fully Qualified Name Resolving for ClassTypes

### ISSUE THREAD

**Issue by JonasKlauke** [soot-oss/SootUp#682]
- [x] support multi-release jars which have classes in META-INF
- ~~extract the fully qualified name instead of using the path~~ chicken/egg problem

**Comment by swissiety** [comment]
i.e. fix AnalysisInputLocations:
- [x] move `IdentifierFactory.fromPath()` into respective PathBased....Location
- [x] have a `fromPath()` overload in MultiRelease...Location which removes the META-INF folder from name generation
- [x] add a check to compare the given ClassType and the parsed ClassType in the ByteCodeFrontend

**Comment by JonasKlauke** [comment]
this issue is kind of connected with #713

**Comment by JonasKlauke** [comment]
path preambles can probably be created by checking every .jar file in a jar and saving that as preamble and we can define some preambles from popular frameworks like spring boot.

So we dont need more specialized inputlocations
