### ISSUE TITLE
Excpetions in MethodDispatchResolver

### ISSUE THREAD

**Issue by Liyw979** [soot-oss/SootUp#705]
inside `resolveConcreteDispatch`
```
      ClassType finalSuperClassType = superClassType;
      SootClass<?> superClass =
          view.getClass(superClassType)
              .orElseThrow(
                  () ->
                      new ResolveException(
                          "Did not find class " + finalSuperClassType + " in View"));

      classesInHierachyOrder.add(superClass);
```
A `ResolveException` was thrown and it will skip the searching of default methods.
Can I make a PR to remove this throw in `resolveConcreteDispatch`?

**Comment by swissiety** [comment]
this seems reasonable. i.e. not failing completely, working with the information we have (given in the setup).

When you are at it maybe you can simplify the code and replace the calls to findConcreteMethodInSootClass( sootClass, methodSignature ) to sootClass.getMethod(subsignature) as well as they are equivalent.

**Comment by Liyw979** [comment]
nice tip @swissiety
