### ISSUE TITLE
IR building fail to halt in some test cases

### ISSUE THREAD

**Issue by ayanamists** [soot-oss/SootUp#714]
Dear SootUp team,

I am currently using SootUp to analyze some real-world programs, and I have encountered some issues with the untyped IR building algorithm, LocalSplitter, and TypeAssigner. Specifically, these components fail to halt in some test cases, such as when I tested with jre11. 

+ `jdk.internal.jimage.ImageStringsReader :: mutf8FromString` will cause `LocalSplitter` not halt / comsume unreasonable time
+ `java.lang.Character$UnicodeScript :: <clinit>` will cause `TypeAssigner` not halt / comsume unreasonable time. It seems that the real problem occurs in the `LocalNameStandardizer`.
+ `sun.jvm.hotspot.ui.classbrowser.HTMLGenerator :: genHTMLListForFields`, with desc `(Lsun/jvm/hotspot/oops/InstanceKlass;)Ljava/lang/String;`,  will cause `AsmMethodSource :: convert` not halt / comsume unreasonable time. It worth noting that the worklist will be full of elements, even through the length of `instructions` list is just `172`. Please refer to the attached screenshot for more details.

<img width="721" alt="截屏2023-10-23 11 36 14" src="https://github.com/soot-oss/SootUp/assets/44194981/4545bd61-c253-4af4-9ce7-f2468536ee85">

I would like to suggest performing some tests before releasing this framework, as the failed/unhalted cases are numerous and cannot be excluded by hand. I hope this feedback is helpful in improving the quality of SootUp.

The sootup version I used:

```kotlin
implementation("org.soot-oss:sootup.core:1.1.2")
implementation("org.soot-oss:sootup.java.core:1.1.2")
implementation("org.soot-oss:sootup.java.sourcecode:1.1.2")
implementation("org.soot-oss:sootup.java.bytecode:1.1.2")
implementation("org.soot-oss:sootup.jimple.parser:1.1.2")
implementation("org.soot-oss:sootup.callgraph:1.1.2")
implementation("org.soot-oss:sootup.analysis:1.1.2")
```

The jre11 version info:

```
IMPLEMENTOR="Oracle Corporation"
IMPLEMENTOR_VERSION="18.9"
JAVA_VERSION="11"
JAVA_VERSION_DATE="2018-09-25"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.vm.ci jdk.management jdk.unsupported jdk.internal.vm.compiler jdk.aot jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:76072a077ee1"
```

**Comment by JonasKlauke** [comment]
Thanks for the report. You can help to improve SootUp by adding your specific failures as test cases in pull request.
