### ISSUE TITLE
Enable to check if an interface method is a default method

### ISSUE THREAD

**Issue by JonasKlauke** [soot-oss/SootUp#727]
Normal interface methods have a body in Bytecode. Therefore, it is not clear if an interface method has a body generated by the compiler or if the body was actually implemented in a default method.

Enable to check if a method is default or set normal interface methods as abstract methods

**Comment by JonasKlauke** [comment]
Default methods are not marked as default in bytecode. But invokes of these methods are done using invokevirtual instead of invokeinterface

Default method call
```
        8: aload_1
        9: invokevirtual #4                  // Method target:()V
       12: return
```

Interface method call
```
         8: aload_1
         9: invokeinterface #4,  1            // InterfaceMethod j8dim2/Interface.method:()V
        14: return
```

**Comment by swissiety** [comment]
A body implementation from a default method is only stored in the interface and not in the sootclass again.. so just check where you loaded the body from?

--- background/sidenote:

A Sootclass (which can represent an interface) only stores 'additional' information - thats why the `MethodDispatcher` exists. We have no method accumulating SootClass, which stores & agggregates (or forwards to) that information (, yet?) Maybe should implement a method in SootClass that returns `Map<MethodSignature, Body>` that collects this information (i.e. where the body comes from and the respective `Body`)?

**Comment by JonasKlauke** [comment]
The problem is a "abstract" Interface Method and a default Interface Method have a body in bytecode. I started to investigate if they are somehow marked but I did not find anything. So if you create an empty default method it looks like a "abstract" Interface Method in bytecode

**Comment by JonasKlauke** [comment]
My bad. Normal Interface methods dont have a body. I somehow checked two empty default methods :D
normal interface methods are marked as abstract.

But this issue will still fix that we do not resolve to abstract methods
