### ISSUE TITLE
PathBasedAnalysisInputLocation, JavaClassPathAnalysisInputLocation - what are the differences between them?

### ISSUE THREAD

**Issue by slimming-fat** [soot-oss/SootUp#743]
If I want to analyze the **jar**, which one should I choose？

**Comment by swissiety** [comment]
JavaClassPathAnalysisInputLocation is a wrapper for the PathBasedAnalysisInputLocation - so you can use both for that purpose but it is intended to use the JavaClassPathAnalysisInputLocation.
