### ISSUE TITLE
Publish snapshots to maven

### ISSUE THREAD

**Issue by kadirayk** [soot-oss/SootUp#760]
merges to dev should trigger publishing a snapshot version at maven automatically.

**Comment by Liyw979** [comment]
![image](https://github.com/soot-oss/SootUp/assets/16919236/b5a08619-767d-4df6-b729-6d2c4334969b)
This is enough for me. Really nice!

**Comment by JonasKlauke** [comment]
yeah that is one fast solution, but if we remember our problems with dex2jar and jitpack, we should still work on a published snapshot built from here 
Edit : but this will simplyfy to ask people to try the current dev branch version

**Comment by Liyw979** [comment]
Is this done? Where can I find snapshots in maven repository?

**Comment by jpstotz** [comment]
@Liyw979 Just look into pom.xml and you will see the configured snapshot repository:

https://github.com/soot-oss/SootUp/blob/f55355178cca60990c02d58b7ba3dd74df1b64aa/pom.xml#L416-L419

https://oss.sonatype.org/#nexus-search;gav~org.soot-oss~sootup.analysis~~~~kw,versionexpand
