### ISSUE TITLE
How long does it support merge switch statements in TODOs?

### ISSUE THREAD

**Issue by yongxin3344520** [soot-oss/SootUp#762]
I would like to ask： How long does it support merge switch statements in TODOs?
Thanks！

**Comment by swissiety** [comment]
Hi @yongxin3344520
I did not understand your question - can you please rephrase the question?

**Comment by yongxin3344520** [comment]
Sorry，What I mean is : How long does it support merge switch statements in your TODOs?
You can find it in https://github.com/soot-oss/SootUp/wiki/TODOs
![image](https://github.com/soot-oss/SootUp/assets/31799392/d62a1be1-9274-4a2b-9bbe-adeef0b6f044)

**Comment by stschott** [comment]
Hi, we support it since the first release of SootUp.
