### ISSUE TITLE
built failed with gradle 

### ISSUE THREAD

**Issue by zhu1971** [soot-oss/SootUp#767]
System: mac
Gradle version: v8.5
SootUp: v1.1.2
Failed message(via gradle):
Execution failed for task ':app:compileScala'.
> Could not resolve all files for configuration ':app:compileClasspath'.
   > Could not find com.github.ThexXTURBOXx.dex2jar:dex-tools:v61.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/ThexXTURBOXx/dex2jar/dex-tools/v61/dex-tools-v61.pom
     Required by:
         project :app > org.soot-oss:sootup.java.bytecode:1.1.2

**Comment by JonasKlauke** [comment]
you could try this fix
https://github.com/soot-oss/SootUp/discussions/687#discussioncomment-7701548

**Comment by zhu1971** [comment]
> you could try this fix [#687 (comment)](https://github.com/soot-oss/SootUp/discussions/687#discussioncomment-7701548)

Thank you for sharing the infomation! It has been resolved with the info.
