### ISSUE TITLE
Compatibility Issue with Java 18 in SootUp: Unsupported Class File Major Version 62

### ISSUE THREAD

**Issue by PhoenixMallu** [soot-oss/SootUp#771]
I am encountering a compatibility issue when using SootUp with Java 18. The specific error is 'Unsupported class file major version 62,' suggesting that the ASM library version included in SootUp does not support Java 18 class files. I've checked the pom.xml of SootUp and couldn't find an explicit declaration of the ASM version being used. This is causing difficulties in analyzing Java 18 compiled classes. Could you please provide information on the ASM version used in SootUp, or suggest a way to resolve this compatibility issue?

**Comment by stschott** [comment]
You should try to use the most recent SootUp version by cloning and building the develop branch instead of using the latest release on Maven Central.
