### ISSUE TITLE
Jimple file is error

### ISSUE THREAD

**Issue by slimming-fat** [soot-oss/SootUp#804]
I used **sootUp develop** to convert.class files to jimple files, but found that the converted jimple had problems.
The decompiled bytecode is as follows:
![image](https://github.com/soot-oss/SootUp/assets/126549527/c8e6672d-da51-4012-b9de-4b703817938d)

The converted jimple is as follows:

![image](https://github.com/soot-oss/SootUp/assets/126549527/5b61896a-a49e-4bb9-85cb-db3ed0e5a27d)

There was an error in the conversion to the **$lastDotIndex** variable because **java.lang.Class** was converted to **int**.

But, the jimple file generated by **Soot** is fine. The converted jimple is as follows:

![image](https://github.com/soot-oss/SootUp/assets/126549527/b71e405f-8fcc-47a8-b098-72dcf706ba68)

Decompiled bytecode is as follows:
```java
public void prepare() throws ClassNotFoundException, NoSuchMethodException {
        String targetMethod;
        if (this.staticMethod != null) {
            int lastDotIndex = this.staticMethod.lastIndexOf(46);
            if (lastDotIndex == -1 || lastDotIndex == this.staticMethod.length()) {
                throw new IllegalArgumentException("staticMethod must be a fully qualified class plus method name: e.g. 'example.MyExampleClass.myExampleMethod'");
            }

            targetMethod = this.staticMethod.substring(0, lastDotIndex);
            String methodName = this.staticMethod.substring(lastDotIndex + 1);
            this.targetClass = this.resolveClassName(targetMethod);
            this.targetMethod = methodName;
        }

        Class<?> targetClass = this.getTargetClass();
        targetMethod = this.getTargetMethod();
        Assert.notNull(targetClass, "Either 'targetClass' or 'targetObject' is required");
        Assert.notNull(targetMethod, "Property 'targetMethod' is required");
        Object[] arguments = this.getArguments();
        Class<?>[] argTypes = new Class[arguments.length];

        for(int i = 0; i < arguments.length; ++i) {
            argTypes[i] = arguments[i] != null ? arguments[i].getClass() : Object.class;
        }

        try {
            this.methodObject = targetClass.getMethod(targetMethod, argTypes);
        } catch (NoSuchMethodException var6) {
            this.methodObject = this.findMatchingMethod();
            if (this.methodObject == null) {
                throw var6;
            }
        }
  }
```

**Comment by swissiety** [comment]
Hi @slimming-fat,
as far as I see the type of $lastDotIndex is **unknown** (!= int)?
which version of SootUp did you use?
If you wish to have typed Jimple (i.e. have Locals with the type inferred) you need to apply the `BodyInterceptor` `TypeAssigner`.

**Comment by slimming-fat** [comment]
> Hi @slimming-fat, as far as I see the type of $lastDotIndex is **unknown** (!= int)? which version of SootUp did you use? If you wish to have typed Jimple (i.e. have Locals with the type inferred) you need to apply the .`BodyInterceptor``TypeAssigner`

Hi @swissiety,
I use SootUp develop.
The type of **$lastDotIndex** in the same method cannot be **java.lang.Class** and **int**.

**Comment by swissiety** [comment]
Ah I see, the use with +1 - thanks for reporting that finding :)

**Comment by swissiety** [comment]
Investigated the bytecode - the Local index is reused by the JVM and therefore points to the same Location. Applying the `BodyInterceptor` `Localsplitter` should split this situation into multiple Locals.

**Comment by slimming-fat** [comment]
> Investigated the bytecode - the Local index is reused by the JVM and therefore points to the same Location. Applying the should split this situation into multiple Locals.`BodyInterceptor``Localsplitter`

Hi, for the same project, it takes only 30 seconds to generate jimple without using Localsplitter. However, when using Localsplitter, it hasn't generated jimple even after 20 minutes. I suspect that Localsplitter is too complex.
[issues#798](https://github.com/soot-oss/SootUp/issues/798)

**Comment by swissiety** [comment]
yes, unfortunately the `LocalSplitter` implementation has bugs that are currently investigated by #798 but this would be the general way - after fixing that a List of BodyInterceptors will be enabled by default to prevent those situations.
