### ISSUE TITLE
com.ibm.wala.util.debug.UnimplementedError: Unhandled JDT node type org.eclipse.jdt.core.dom.LambdaExpression

### ISSUE THREAD

**Issue by 75ACOL** [soot-oss/SootUp#816]
When I try to import such source code, an error occurs.

```
import java.util.ArrayList;
import java.util.List;

class Foo {
    public static void main(String[] args) {
        List<String> stringList = new ArrayList<>();
        stringList.add(args[0]);
        stringList.forEach(str -> {
            System.out.println(str);
        });
    }
}
```

**Comment by stschott** [comment]
Please compile the code you want to analyze before handing it to SootUp. The source code frontend is only experimental and does not support the uncompiled Lamba expression within your code snippet. Check our documentation for reference (https://soot-oss.github.io/SootUp/v1.1.2/getting-started/).
