### ISSUE TITLE
documentation: Localsplitter - locals can be reassigned to the same LocalIdx and therefore get the same Jimple Local assigned

### ISSUE THREAD

**Issue by Liyw979** [soot-oss/SootUp#836]
![image](https://github.com/soot-oss/SootUp/assets/16919236/e74d751b-dd64-499f-a705-9ccc1916fb83)
`example` and `getUuid` are at different branches, but the jimple code is
![image](https://github.com/soot-oss/SootUp/assets/16919236/3ad5a116-314d-417c-9454-28acbe138543)

**Comment by swissiety** [comment]
Do you mean userId and example (which are in different Java scopes) are assigned to the same Local in Jimple?

Unfortunately the shared amount of information is so censored that it is not really comprehensible. Please try to share some more information - especially more generated Jimple code would be helpful.

**Comment by JonasKlauke** [comment]
We understand that sharing sensitive data might be problematic.
Could you try to mock this example, so you probably wont share much internal stuff, because it is really hard to understand the issue 😅

**Comment by Liyw979** [comment]
I do try to reproduce with simple java code, but saddly can't.
I mean `Example example` is defined in the first branch, which can't be assigned with the return value of getUuid() in else branch.
![image](https://github.com/soot-oss/SootUp/assets/16919236/874353db-6032-4927-9202-b17678770482)
In java code, `String userId` is the one `getUuid()` gose to.

**Comment by stschott** [comment]
Can you at least give us the corresponding excerpt of the bytecode?

**Comment by swissiety** [comment]
If it is the situation i mentioned then the `Localsplitter` should handle these situations (currently maybe not as the Localsplitter is currently reimplemented more close to the version that is used in soot)

**Comment by JonasKlauke** [comment]
Liyw compiles with Debug information, So the bytecode also contains the names of the variables which SootUp takes. But since there is a branch the local variables with the index 1 is in the if branch example and in the else branch userID. Since SootUp's Localsplitter still has problem (? I guess 😄) and since SootUp only takes the first name for the index of a local variable, the if and else branch use the local variable name example

**Comment by Liyw979** [comment]
Finally reproduced with the tip by @JonasKlauke , but I am not using `Localsplitter`

complie the following code with `javac -p`
```
import java.util.*;
class Main {
    static void main(String[] args) {
        if (args.length > 0){
            Set<Integer> aaaaaaaa = new HashSet<>() ;
            aaaaaaaa.add(1);
        } else {
            List<Integer> bbbbbbbb = new ArrayList<>();
            bbbbbbbb.add(1);
            System.out.println(bbbbbbbb);
        }
    }
}
```

sootupVersion = "develop-0e7e27d457-1"

jimple 
```
{
    java.lang.String[] args;
    unknown $stack2, $stack3, $stack4, $stack5, $stack6, $stack7, aaaaaaaa;


    args := @parameter0: java.lang.String[];
    $stack2 = lengthof args;

    if $stack2 <= 0 goto label1;
    $stack6 = new java.util.HashSet;
    specialinvoke $stack6.<java.util.HashSet: void <init>()>();
    aaaaaaaa = $stack6;
    $stack7 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>(1);
    interfaceinvoke aaaaaaaa.<java.util.Set: boolean add(java.lang.Object)>($stack7);

    goto label2;

  label1:
    $stack3 = new java.util.ArrayList;
    specialinvoke $stack3.<java.util.ArrayList: void <init>()>();
    aaaaaaaa = $stack3;                                             <------- should be bbbbbbbb
    $stack4 = staticinvoke <java.lang.Integer: java.lang.Integer valueOf(int)>(1);
    interfaceinvoke aaaaaaaa.<java.util.List: boolean add(java.lang.Object)>($stack4);
    $stack5 = <java.lang.System: java.io.PrintStream out>;
    virtualinvoke $stack5.<java.io.PrintStream: void println(java.lang.Object)>(aaaaaaaa);

  label2:
    return;
}
```

```
    val view = JavaView(PathBasedAnalysisInputLocation.create(path, SourceType.Application))
    val sig = view.getIdentifierFactory.parseMethodSignature("<Main: void main(java.lang.String[])>")
    println(view.getMethod(sig).get().getBody)
```

**Comment by swissiety** [comment]
Thank you for your efforts explaining the problem.

This behaviour is known to us - for those kind of inputs the Localsplitter is needed to be applied - the `BodyInterceptors` that are needed to create improved Jimple will be enabled by default when they run more reliably.

I think we should add an example based on this to the documentation of the LocalSplitter. #documentation
