### ISSUE TITLE
fix TypeAssigner

### ISSUE THREAD

**Issue by swissiety** [soot-oss/SootUp#853]
- [ ] RuntimeJarConversionTests.testZoneInfoFile_getZoneInfo() fails:
```
Caused by: java.lang.ClassCastException: sootup.core.jimple.basic.Local cannot be cast to sootup.core.jimple.common.ref.JArrayRef
	at sootup.java.bytecode.interceptors.typeresolving.CastCounter.addUpdatedValue(CastCounter.java:176)
	at sootup.java.bytecode.interceptors.typeresolving.CastCounter.visit(CastCounter.java:134)
	at sootup.java.bytecode.interceptors.typeresolving.TypeChecker.caseAssignStmt(TypeChecker.java:195)
```

- [ ] fix handling of Locals that exist in `BodyBui.der.getLocals()` but do not exist (anymore) in the stmts - just ignore them then.

**Comment by guiyj** [comment]
I found another example that may relate to the TypeAssigner.

SootUp Version: 1.2.0, commit 917133e.

For the following method (extracted from `jre 1.6.0_45`): 
```
<java.util.ArrayList: boolean add(java.lang.Object)> {
    java.lang.Object l1;
    java.util.ArrayList l0;
    unknown $stack2, $stack3, $stack4, $stack5, $stack6;


    l0 := @this: java.util.ArrayList;
    l1 := @parameter0: java.lang.Object;
    $stack2 = l0.<java.util.ArrayList: int size>;
    $stack3 = $stack2 + 1;
    virtualinvoke l0.<java.util.ArrayList: void ensureCapacity(int)>($stack3);
    $stack6 = l0.<java.util.ArrayList: java.lang.Object[] elementData>;
    $stack4 = l0.<java.util.ArrayList: int size>;
    $stack5 = $stack4 + 1;
    l0.<java.util.ArrayList: int size> = $stack5;
    $stack6[$stack4] = l1;

    return 1;
}
```
After applying `LocalSplitter` and `TypeAssinger` to this method, it becomes: 
```
<java.util.ArrayList: boolean add(java.lang.Object)> {
    int $stack2, $stack3, $stack4, $stack5;
    java.lang.Object l1;
    java.lang.Object[] $stack6;
    java.util.ArrayList l0;


    l0 := @this: java.util.ArrayList;
    l1 := @parameter0: java.lang.Object;
    $stack2 = l0.<java.util.ArrayList: int size>;
    $stack3 = $stack2 + 1;
    virtualinvoke l0.<java.util.ArrayList: void ensureCapacity(int)>($stack3);
    $stack6 = l0.<java.util.ArrayList: java.lang.Object[] elementData>;
    $stack4 = l0.<java.util.ArrayList: int size>;
    $stack5 = $stack4 + 1;
    l0.<java.util.ArrayList: int size> = $stack5;
    $stack4[$stack4] = l1;

    return 1;
}
```
In the second-to-last line (the line just before `return 1;`), we can see that it tries to store `l1` into an `int` variable `$stack4`, which is expected to be `$stack6[$stack4] = l1;`. No exceptions were thrown.

**Comment by guiyj** [comment]
After resolving type, `SootUp` knows that `$stack4` is of `int` type, and `$stack6` is of `java.lang.Object[]` type.

Now it is going to perform `replaceLocal($stack4<unknown>, $stack4<int>)` for the stmt `$stack6<unknown>[$stack4<unknown>] = l1;`.

First, uses will be replaced, result: `$stack6<unknown>[$stack4<int>] = l1;`.

After that, defs will be replaced. For a given `JArrayRef`, its uses include: base's uses, base, index's uses and index. So `SootUp` tries to replace `$stack4<unknown>` with `$stack4<int>` in `JArrayRef: $stack6<unknown>[$stack4<int>]`.

https://github.com/soot-oss/SootUp/blob/917133e974c6c377d573dfbb291c299838a40551/sootup.core/src/main/java/sootup/core/model/Body.java#L379

However, this will replace `$stack6<unknown>` by `$stack4<int>` incorrectly, as `SootUp` only considers the base when replacing def for `JArrayRef`, result: `$stack4<int>[$stack4<int>] = l1;`.

https://github.com/soot-oss/SootUp/blob/917133e974c6c377d573dfbb291c299838a40551/sootup.core/src/main/java/sootup/core/jimple/common/stmt/JAssignStmt.java#L244
