### ISSUE TITLE
Call graph missed an invocation in interface

### ISSUE THREAD

**Issue by kitty-1998** [soot-oss/SootUp#917]
Hi, I found a code example which can help improve SootUp. See the minimized code example below:

```java
package edu.kitty;
public class Main {
    public static void main(String[] args) {
        Inner i = (a) -> a%7;
        System.out.println(i.bar(1));
    }
    interface Inner {
        int bar(int a);
    }
}
```
The method `main` called `bar` and call graph should have this edge, but I used CHA algorithm to construct the call graph and found no callee target of `main`.

My SootUp version: develop-5af272dcda

**Comment by JonasKlauke** [comment]
Hi Kitty, the underlying issue is the missing Methodhandle support.
Could you post your use case of Methodhandles in #906?
Because this is a duplicate issue.

**Comment by JonasKlauke** [comment]
duplicate
