### ISSUE TITLE
Is there an API like entryInitialFlow?

### ISSUE THREAD

**Issue by VonLYC** [soot-oss/SootUp#934]
### What happened?

I'm a beginner in program analysis, and I'm using SootUp to implement available expression analysis. In Soot, I can use newInitialFlow and entryInitialFlow to set different OUTPUT for regular basic blocks and the entry. Does SootUp have a similar API? If not, is it possible to add this feature in future versions?

### Version

Latest develop branch

**Comment by swissiety** [comment]
Hi @VonLYC,
currently `entryInitialFlow()` is not ported, yet. We are happy if you like to contribute a PR to add it to the API.
