### ISSUE TITLE
[Bug]: Potential Issue in getType Method of JUshrExpr.java

### ISSUE THREAD

**Issue by Momo-Not-Emo** [soot-oss/SootUp#960]
### What happened?

Dear SootUp Developers,

I have identified a potential issue in the `getType` method of `JUshrExpr` located at [JUshrExpr.java: L56](https://github.com/soot-oss/SootUp/blob/develop/sootup.core/src/main/java/sootup/core/jimple/common/expr/JUshrExpr.java#L56).

In [the original Soot code](https://github.com/soot-oss/soot/blob/develop/src/main/java/soot/jimple/internal/JUshrExpr.java#L60), the `getType` method is implemented as follows:

```java
@Override
public Type getType() {
  if (isIntLikeType(op2Box.getValue().getType())) {
    final Type t1 = op1Box.getValue().getType();
    if (isIntLikeType(t1)) {
      return IntType.v();
    }
    final LongType tyLong = LongType.v();
    if (tyLong.equals(t1)) {
      return LongType.v();
    }
  }
  return UnknownType.v();
}
```

However, in the refactored version in SootUp, the code is:

```java
@Nonnull
@Override
public Type getType() {
  Value op1 = getOp1();
  Value op2 = getOp2();

  if (Type.isIntLikeType(op2.getType())) {
    return UnknownType.getInstance();
  }

  if (Type.isIntLikeType(op1.getType())) {
    return PrimitiveType.getInt();
  }
  if (op1.getType().equals(PrimitiveType.getLong())) {
    return PrimitiveType.getLong();
  }

  return UnknownType.getInstance();
}
```

I believe there is a logical error in the condition: 

```java
if (Type.isIntLikeType(op2.getType())) {
  return UnknownType.getInstance();
}
```

It should be:

```java
if (!Type.isIntLikeType(op2.getType())) {
  return UnknownType.getInstance();
}
```

This is consistent with other similar `getType` method implementations, such as the one found in [JShrExpr.java: L57](https://github.com/soot-oss/SootUp/blob/develop/sootup.core/src/main/java/sootup/core/jimple/common/expr/JShrExpr.java#L57).

### Version

Latest develop branch

**Comment by swissiety** [comment]
thx for finding this :+1: PR is on the way!
