### ISSUE TITLE
[Bug]: The translation of variable in to different format 

### ISSUE THREAD

**Issue by PhoenixMallu** [soot-oss/SootUp#966]
### What happened?

for the simple code given below:
public class SampleB implements SampleA {
    @Override
    public void testB(int arg1, int arg2) {
        if (arg1 > 10) {
            arg2 = arg1;
        }
    }
}
Jimple generated by Sootup is :
(0) this := @this: com.example.myapp.Tests.SampleB
(1) arg1 := @parameter0: int
(2) arg2#0 := @parameter1: int
(3) if arg1 <= 10 goto label0
(4) arg2#1 = arg1
(5) label0: return

variable arg2 is getting translated in to arg2#0  and arg2#1 . Can anyone tell me why this is happening with the ;later version of Sootup , but it was not happening with earlier version of Sootup. (one released in December 2023)

This has made my tool quite difficult to run as now I am not able to correctly track the variable arg2. It gets translated in to arg2#0 and arg2#1 affecting my taint tracking logic. 

### Version

Latest develop branch

**Comment by swissiety** [comment]
Hi,
with the current release BodyInterceptors are applied by default, to create semantically improved/valid Jimple. You can disable them in the `AnalysisInputLocation`s contructor.

**Comment by PhoenixMallu** [comment]
Hi will it impact the temporary variable translation like the translation of temporary variables used in a for loop (for int i = 0, i < ... ) where "I" gets wrongly translated as some local variable declared just before the for loop?

**Comment by swissiety** [comment]
what do you mean with wrongly translated?
The scope of a Local in Jimple is the complete Method as Jimple does not support blocks / nesting of blocks.

**Comment by PhoenixMallu** [comment]
Sorry for lack of clarity. The earlier version of Sootup released in December was having following issue :

The issue is for the following Java code :

int bitValue = 0;
for (int j = 0; j < 32; j++)
{
bitValue ^= (help >>> j) & 1;
}

Jimple generated is :
(34) $j = 0
(35) $j = 0
(36) if $j >= 32
(37) $stack24 = $help >>> $j
(38) $stack25 = $stack24 & 1
(39) $j = $j ^ $stack25
(40) $j = $j + 1
(41) goto

Where the variable "bitValue" in the original code was replaced with a temporary variable "j" as can be seen in Jimple line 34 and the temporary variable "j" used in the loop  is correctly translated as "j" itself in Jimple in line 35.  (This is the variable reuse I observed in older version of SootUp) 

But after updating Sootup to its latest version this problem was resolved but still the variable mapping lacks clarity especially when we are using objects. The references to objects in Java gets translated in Sootup in two stages. The first stage involves mapping the referenced instance to a temporary stack variable then second stage involves assigning this stack variable to the original reference of the object. Now, when any method in the class referenced by the variable is called, Sootup seems to choose randomly from either the actual reference variable or the intermediate stack variable in its invoke expressions.  

Similarly, when we are handling simpler codes with primitive data types the arguments itself gets translated along the sidelines of  (Static Single Assignment) .  I might be totally wrong, but these are some of my obeservations as I have been finding these features impacting my taint tracking model and logic. It would be great if you could suggest me some resources/ documentation of Sootup for understanding the variable translation logic applied in Sootup.

**Comment by swissiety** [comment]
Currently (1.3.0) the source snippet generates:
```
this := @this: B;
l1 = 31;
l2 = 0;
l3 = 0;

label1:
if l3 >= 32 goto label2;
$stack4 = 31 >>> l3;
$stack5 = $stack4 & 1;
l2 = l2 ^ $stack5;
l3 = l3 + 1;

goto label1;

label2:
return;
```
which is valid as you claimed. which seemed more of a sidenote which used Locals named $stack and with the other naming scheme?
Ok the situation you described (If I understood correctly) is that the naming of `Local`s differs from the variable names in the sourcecode and that there are multiple locals referencing them?

Explaination of the Situation :
The bytecode reuses stack positions (which will be translated to Locals) therefore a 1:1 mapping from variable to Locals is not possible in a trivial way. To optimizie/normalize the raw Jimple `BodyInterceptor`s are applied.
Have a look into [Documentation/Bodyinterceptors](https://soot-oss.github.io/SootUp/latest/bodyinterceptors/) for more information.
Especially the LocalSplitter tries to tackle the Local that reuse problem. It creates a new Local when it detects a reuse. Sometimes its even necessary as e.g. pimary datatypes an objects are assigned the same memory locations via the bytecode which results in semantically invalid raw jimple.
