### ISSUE TITLE
[Bug]: Resolve local variables within the method to unknown type

### ISSUE THREAD

**Issue by sdlisilong** [soot-oss/SootUp#992]
### What happened?

Why is the local variable type unknown within the parsing method？

I use soot version is 1.3.0

execute class：
`public static void main(String[] args) throws Exception {

        URL resource = Main.class.getResource("/");

        File file = new File(resource.toURI());

        JavaClassPathAnalysisInputLocation inputLocation = new JavaClassPathAnalysisInputLocation(file.getAbsolutePath());

        // Create a view for project, which allows us to retrieve classes
        View view = new JavaView(inputLocation);

        ClassType classType = view.getIdentifierFactory().getClassType("com.javaparser.TestClass");

        SootClass sootClass = view.getClass(classType).get();

        System.out.println(sootClass);

        Set<? extends SootMethod> methods = sootClass.getMethods();

        for (SootMethod method : methods) {
            System.out.println(method.getBody());
        }

    }`

Parsed class：
`public class TestClass {
    int i = 0;

    public void t() {
        int j = 0;
        System.out.println("test class");
    }
}`

result：
`{
    com.javaparser.TestClass this;
    unknown $stack2, j;

    this := @this: com.javaparser.TestClass;
    j = 0;
    $stack2 = <java.lang.System: java.io.PrintStream out>;
    virtualinvoke $stack2.<java.io.PrintStream: void println(java.lang.String)>("test class");

    return;
}`

### Version

1.3.0

**Comment by stschott** [comment]
Did you add the Java runtime to your input locations as described [here](https://soot-oss.github.io/SootUp/latest/analysisinput/)?

**Comment by sdlisilong** [comment]
> Did you add the Java runtime to your input locations as described [here](https://soot-oss.github.io/SootUp/latest/analysisinput/)?

thank you!，Based on your suggestion,i find problem! related to TypeAssigner of BodyInterceptor
